# Generated by Django 3.2.5 on 2021-09-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
